#!/bin/bash
pushd /opt/sites/rails/btdotcom 2>/dev/null
echo "************************"
echo "Deploying application..."
echo "************************"

git reset --hard
echo "************************"
echo "Restarting application"
echo "************************"
env
./stop.sh
./start.sh
popd 2>/dev/null

echo "Application is now deployed!"
