#!/usr/bin/env ruby
# Copy to .git dir and rename to pre-commit

php_file_locations = %{*.php phpdev/*.php}
errors_found = 0
errors = ""
php_file_locations.split.each do |phpfile|
    check_phpscripts = `find #{ENV['GIT_DIR']}/../#{phpfile} -exec php -l {} \\;`
    check_phpscripts.each do |r| 
        if not r =~ /No syntax errors/ then
            if r.length > 3 and not r =~ /Errors parsing/ then
                errors_found += 1
                errors += "Error #{errors_found} : #{r}\n"
            end
        end
    end
end

# Block the commit for these conditions
# 1. PHP compilation error
if errors_found > 0 then
    puts "There are syntax errors found"
    puts "---"
    puts "#{errors}"
    puts "---"
    puts "Please correct these and resubmit"
    exit 1
else
    exit 0
end

